/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Codigo.Eco_lombia;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author felipe-c4
 */
public class InterEcoparques extends javax.swing.JPanel {
    
    boolean BInteres=false;
    boolean BEcosistema=false;
    boolean BidRegistro=false;
    boolean BUbicación=false;
    
    
    JPanel inicio;
    BusquedaResultados busquedaResultados;
    String ConcatLook=null;
    Ventana ventana;
    
    public InterEcoparques(Ventana ventana,JPanel inicio) {
        initComponents();
        this.inicio = inicio;
        busquedaResultados=new BusquedaResultados(ventana,inicio,this);
        this.ventana=ventana;
        ventana.add(this);
        this.setVisible(false);
        this.setBounds(0, 0, 1000, 800);
        arranque();
    }

    public void arranque(){
        
        BInteres=false;
        BEcosistema=false;
        BidRegistro=false;
        BUbicación=false;
        
        JCBEcosistema.setEnabled(false);
        JCBInteres.setEnabled(false);
        JCBUbicacion.setEnabled(false);
        
        JCBInteres.setSelectedIndex(0);
        JCBEcosistema.setSelectedIndex(0);
        JCBUbicacion.setSelectedIndex(0);
        JTFCriterio.setText("");
        JTFCriterio.setEditable(true);
        ConcatLook=null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGOpcBusqueda = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JBatras = new javax.swing.JButton();
        JRTaxonomia = new javax.swing.JRadioButton();
        JREcosistema = new javax.swing.JRadioButton();
        JRIdRegistro = new javax.swing.JRadioButton();
        JRUbicacion = new javax.swing.JRadioButton();
        JCBEcosistema = new javax.swing.JComboBox<>();
        JCBInteres = new javax.swing.JComboBox<>();
        JCBUbicacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JTFCriterio = new javax.swing.JTextField();
        JBBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 120, 120));
        setMaximumSize(new java.awt.Dimension(250, 250));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("-");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 222, 1));
        jLabel2.setText("ECO");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 237, 67));
        jLabel3.setText("LOM");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 155, 253));
        jLabel4.setText("BI");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 44, 29));
        jLabel5.setText("A");

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/BEcoparques.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel7)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("RED COLABORATIVA PARA LA BIODIVERSIDAD Y ECOPARQUES COLOMBIANOS");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("B U S C A R      P O R :");

        JBatras.setBackground(new java.awt.Color(231, 231, 231));
        JBatras.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        JBatras.setText("Atras");
        JBatras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        JBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatrasActionPerformed(evt);
            }
        });

        JRTaxonomia.setBackground(new java.awt.Color(120, 120, 120));
        BGOpcBusqueda.add(JRTaxonomia);
        JRTaxonomia.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JRTaxonomia.setForeground(new java.awt.Color(254, 254, 254));
        JRTaxonomia.setText("Interes");
        JRTaxonomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRTaxonomiaActionPerformed(evt);
            }
        });

        JREcosistema.setBackground(new java.awt.Color(120, 120, 120));
        BGOpcBusqueda.add(JREcosistema);
        JREcosistema.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JREcosistema.setForeground(new java.awt.Color(254, 254, 254));
        JREcosistema.setText("Ecosistema");
        JREcosistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JREcosistemaActionPerformed(evt);
            }
        });

        JRIdRegistro.setBackground(new java.awt.Color(120, 120, 120));
        BGOpcBusqueda.add(JRIdRegistro);
        JRIdRegistro.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JRIdRegistro.setForeground(new java.awt.Color(254, 254, 254));
        JRIdRegistro.setText("ID Registro");
        JRIdRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRIdRegistroActionPerformed(evt);
            }
        });

        JRUbicacion.setBackground(new java.awt.Color(120, 120, 120));
        BGOpcBusqueda.add(JRUbicacion);
        JRUbicacion.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JRUbicacion.setForeground(new java.awt.Color(254, 254, 254));
        JRUbicacion.setText("Ubicación");
        JRUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRUbicacionActionPerformed(evt);
            }
        });

        JCBEcosistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Bosque Tropical", "Bosque andino", "Complejo Rocoso de los Andes", "Selva Amazonica", "Matorrales", "Paramo", "Humedal", "Lotico", "Manglar", "Desierto", "Formaciones Xericas", "Embalse", "Coral", "Rio", "Lago", "Cienaga", "Estuario" }));
        JCBEcosistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEcosistemaActionPerformed(evt);
            }
        });

        JCBInteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Caminatas", "Camping", "Deportes", "Planes", "Investigacion", "Relajacion", "Turismo" }));
        JCBInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBInteresActionPerformed(evt);
            }
        });

        JCBUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyaca", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés y Providencia", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada" }));
        JCBUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBUbicacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Criterio de busqueda");

        JTFCriterio.setEditable(false);
        JTFCriterio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        JTFCriterio.setText("Aqui va el criterio de busqueda");
        JTFCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCriterioActionPerformed(evt);
            }
        });

        JBBuscar.setBackground(new java.awt.Color(76, 234, 86));
        JBBuscar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        JBBuscar.setForeground(new java.awt.Color(254, 254, 254));
        JBBuscar.setText("Buscar");
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 254, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBatras, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JREcosistema)
                    .addComponent(JRTaxonomia)
                    .addComponent(JRIdRegistro)
                    .addComponent(JRUbicacion))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCBUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBEcosistema, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JTFCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JBatras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRTaxonomia)
                            .addComponent(JCBInteres))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JREcosistema)
                            .addComponent(JCBEcosistema))
                        .addGap(18, 18, 18)
                        .addComponent(JRIdRegistro)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRUbicacion)
                            .addComponent(JCBUbicacion))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(JTFCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JRTaxonomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRTaxonomiaActionPerformed
        arranque();  
        JCBInteres.setEnabled(true);
        JTFCriterio.setEditable(false);
        BInteres=true;
    }//GEN-LAST:event_JRTaxonomiaActionPerformed

    private void JREcosistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JREcosistemaActionPerformed
        arranque();
        JCBEcosistema.setEnabled(true);
        JTFCriterio.setEditable(false);
        BEcosistema=true;
    }//GEN-LAST:event_JREcosistemaActionPerformed

    private void JRIdRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRIdRegistroActionPerformed
        arranque();
         ConcatLook="IdRegistro";
         BidRegistro=true;
    }//GEN-LAST:event_JRIdRegistroActionPerformed

    private void JRUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRUbicacionActionPerformed
        arranque();
        JCBUbicacion.setEnabled(true);
        JTFCriterio.setEditable(false);
        BUbicación=true;
    }//GEN-LAST:event_JRUbicacionActionPerformed

    private void JTFCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCriterioActionPerformed
    }//GEN-LAST:event_JTFCriterioActionPerformed

    private void JBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatrasActionPerformed
        inicio.setVisible(true);
        this.setVisible(false);
        arranque();
        BGOpcBusqueda.clearSelection();
    }//GEN-LAST:event_JBatrasActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
         busquedaResultados.busqueda(ConcatLook+"//"+JTFCriterio.getText());
        if(BInteres){
            busquedaResultados.Ecoparques(Eco_lombia.HeapSortEcoparque(Eco_lombia.busquedaInteresEcoparque(ventana.ecoparque,JCBInteres.getSelectedItem().toString())));
        }else if(BEcosistema){
            busquedaResultados.Ecoparques(Eco_lombia.busquedaEcosistemaEcoparque(ventana.ecoparque,JCBEcosistema.getSelectedItem().toString()));
        }else if(BUbicación){
            busquedaResultados.Ecoparques(Eco_lombia.HeapSortEcoparque(Eco_lombia.busquedaUbicacionEcoparque(ventana.ecoparque,JCBUbicacion.getSelectedItem().toString())));
        }else if(BidRegistro){
            try {
                 busquedaResultados.Ecoparques(Eco_lombia.HeapSortEcoparque(Eco_lombia.busquedaIdEcoparque(ventana.ecoparque, Integer.parseInt(JTFCriterio.getText()))));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Id no valido");
                arranque();
                return;
            }
        }
        
        busquedaResultados.setVisible(true);
        
        this.setVisible(false);
        arranque();
        BGOpcBusqueda.clearSelection();
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void JCBInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBInteresActionPerformed
      ConcatLook="Interes"+"//"+JCBInteres.getSelectedItem().toString();
    }//GEN-LAST:event_JCBInteresActionPerformed

    private void JCBEcosistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEcosistemaActionPerformed
     ConcatLook="Ecosistemas"+"//"+JCBEcosistema.getSelectedItem().toString();
    }//GEN-LAST:event_JCBEcosistemaActionPerformed

    private void JCBUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBUbicacionActionPerformed
     ConcatLook="Ubicacion"+"//"+JCBUbicacion.getSelectedItem().toString();
    }//GEN-LAST:event_JCBUbicacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGOpcBusqueda;
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBatras;
    private javax.swing.JComboBox<String> JCBEcosistema;
    private javax.swing.JComboBox<String> JCBInteres;
    private javax.swing.JComboBox<String> JCBUbicacion;
    private javax.swing.JRadioButton JREcosistema;
    private javax.swing.JRadioButton JRIdRegistro;
    private javax.swing.JRadioButton JRTaxonomia;
    private javax.swing.JRadioButton JRUbicacion;
    private javax.swing.JTextField JTFCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
